version: '3.7'
services:
   postgres:
    image: postgres:latest
    container_name: transactions-postgres
    environment:
      POSTGRES_DB: "crebito"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"